version: "3"

services:

  balancer:
    build:
      context: .
      dockerfile: dockerfile.balancer
    depends_on:
      - memcached
      - app_1
      - app_2
      - app_3
      - app_4
      - app_5
    ports:
      - "80:5000"

  app_1:
    build:
      network: app_1
      context: .
      dockerfile: dockerfile.app
    depends_on:
      - memcached

  app_2:
    build:
      network: app_2
      context: .
      dockerfile: dockerfile.app
    depends_on:
      - memcached
  
  app_3:
    build:
      network: app_3
      context: .
      dockerfile: dockerfile.app
    depends_on:
      - memcached

  app_4:
    build:
      network: app_4
      context: .
      dockerfile: dockerfile.app
    depends_on:
      - memcached

  app_5:
    build:
      network: app_5
      context: .
      dockerfile: dockerfile.app
    depends_on:
      - memcached

  memcached:
    image: memcached:latest